name: Publish Retype powered website to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: retypeapp/action-build@v4
        with:
          key: ${{ secrets.RETYPE_SECRET }}
          output: .retype

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: retype
          folder: .retype
          clean-exclude: pr-preview