name: Publish Retype powered website to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Retype site
        run: |
          dotnet tool install retypeapp --global
          retype build --output .retype --key "${{ secrets.RETYPE_SECRET }}"

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: retype
          folder: .retype
          clean-exclude: pr-preview